# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-27 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Todos', 'Todos'), ('HADS Proyectos', 'HADS Proyectos'), ('Metodologia de la Asignatura', 'Metodologia de la Asingatura'), ('Django', 'Django'), ('Python', 'Python'), ('Alumnado', 'Alumnado'), ('Otras Asignaturas', 'Otras Asignaturas')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='correctChoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('HADS Proyectos', 'HADS Proyectos'), ('Metodologia de la Asignatura', 'Metodologia de la Asingatura'), ('Django', 'Django'), ('Python', 'Python'), ('Alumnado', 'Alumnado'), ('Otras Asignaturas', 'Otras Asignaturas')], default='Hads Proyectos', max_length=18),
        ),
    ]
