# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-27 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180527_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('HADS Proyectos', 'HADS Proyectos'), ('Metodologia de la Asignatura', 'Metodologia de la Asingatura'), ('Django', 'Django'), ('Python', 'Python'), ('Alumnado', 'Alumnado'), ('Otras Asignaturas', 'Otras Asignaturas')], default='Hads Proyectos', max_length=30),
        ),
    ]
